### ISSUE TITLE
Reconcile documentation and actual output

### ISSUE THREAD

**Issue by AntonPetrov** [BGSU-RNA/JAR3D#15]
Need to update Supplementary info and in the user docs after #14 is merged.

1. SEQUENCEOUTPUT

`meanDeficit,medianDeficit` - provided in the output, but not documented.

2. LOOPOUTPUT

Documentation:
```
filename,sequenceId,motifId,passedCutoff,meanCutoffScore,score,interiorEditDistance,fullEditDistance,rotation
```

Real output:
```
filename,identifier,motifId,passedCutoff,meanCutoffScore,score,deficit,interiorEditDistance,fullEditDistance,rotation
```

So sequenceId -> identifier, `deficit` not documented.

**Comment by clzirbel** [comment]
All fixed in the supplementary and in Github.
